package br.com.letscode.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "tarefas")
@Data
public class Tarefa {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;
    private String titulo;
    private String detalhe;
    @DynamoDBTypeConvertedEnum
    private Prioridade prioridade;
    @DynamoDBTypeConvertedTimestamp
    private Date criacao;
    @DynamoDBTypeConvertedTimestamp
    private Date previsao;
    @DynamoDBTypeConvertedTimestamp
    private Date conclusao;
}
